name: API workflow

on: [push, pull_request]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r api/requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@th/fix-oidc
      with:
        use_oidc: true
        flags: backend